### ISSUE TITLE
Global Configurations

### ISSUE THREAD

**Issue by JustinJiaDev** [microservice-tools/pixis#11]
I think you could remove all global variables and use a single global `Configurations` object instead?

https://github.com/microservice-tools/pixis/blob/a610b00821ae167037d2f72dbe76f42196dc5e7f/pixis/configurations.py#L87-L102

Can you move these `global`s to their [original definitions](https://github.com/microservice-tools/pixis/blob/a610b00821ae167037d2f72dbe76f42196dc5e7f/pixis/configurations.py#L8-L83)? I'm not sure if it will work, but I think it should.

**Comment by hodgesrm** [comment]
We discussed something today on the project call. The globals from build.py should end up in a cfg object that's easily accessible to code in the jinja templates.

**Comment by andrew-ni** [comment]
Thanks @JustinJiaDev , change is active and tested on branch **configurations**, will be merged into dev soon!
