### ISSUE TITLE
Other Code Review Feedbacks

### ISSUE THREAD

**Issue by JustinJiaDev** [microservice-tools/pixis#12]
https://github.com/microservice-tools/pixis/blob/a610b00821ae167037d2f72dbe76f42196dc5e7f/pixis/main.py#L18-L23

Can be removed if you follow #9.

> An abstract Language class shows the required methods.

https://github.com/microservice-tools/pixis/blob/a610b00821ae167037d2f72dbe76f42196dc5e7f/pixis/main.py#L27-L28

Now you can try to implement a more complex command line argument parser to support different arguments, etc.

A good practice: [Progressive Disclosure](https://en.wikipedia.org/wiki/Progressive_disclosure)

https://github.com/microservice-tools/pixis/blob/a610b00821ae167037d2f72dbe76f42196dc5e7f/pixis/main.py#L30-L32

Now you can try to implement a way to output text to terminal nicely (e.g. with different color).

https://github.com/microservice-tools/pixis/blob/a610b00821ae167037d2f72dbe76f42196dc5e7f/pixis/main.py#L42-L57

1. Use `pathlib`.
2. It's better to not depend on file extension. You can do something like:

```python
with open(file) as f:
   try:
       return yaml.safe_load(f)
   except yaml.YAMLError as yaml_error:
       try:
           return json.load(f)
       expect ValueError as json_error:
           # or other ways to handle errors
           if extension == "json":
               print(json_error)
           else:
               print(yaml_error)
```

**Comment by andrew-ni** [comment]
Few things left to do: 
- Command line functionality will be finished soon (#20 and also --verbose option)
- we are going to be implementing pathlib for use over os as well

**Comment by andrew-ni** [comment]
All of this is implemented except for colorful printing!
