### ISSUE TITLE
Pixis does not pick local build.py unless you enter -b option

### ISSUE THREAD

**Issue by hodgesrm** [microservice-tools/pixis#20]
I'm developing a new language implementation for Java JAX-RS.  I set up a directory under samples and added a build.py with classes and parameters to implement code generation.  However, when I run `pixis` it generated Python code!  To get pixis to run my local build.py I had to enter `pixis -b build.py`. 

To summarize: if you type `pixis`, it should be the same as running `pixis -b build.py`.

**Comment by andrew-ni** [comment]
Thanks @hodgesrm , this is a simple fix and we were already planning this behavior, but we've just forgotten about this over the past weeks.

**Comment by hodgesrm** [comment]
There's a better way to fix this.  Use default parameter values in the argparse argument definition.  E.g., instead of 
```
parser.add_argument('-b', help="Use your own build file", dest='build_file')
```
use
```
parser.add_argument('-b', help="Set build file location, default: %(default)s", dest='build_file', default='build.py')
```
Another advantage is that help now also prints out the default value, so the citizenry can see what happens if they leave out the flag.

**Comment by hodgesrm** [comment]
Thanks for the quick turnaround @andrew-ni!
