### ISSUE TITLE
Please add a project overview to the README.me

### ISSUE THREAD

**Issue by hodgesrm** [microservice-tools/pixis#3]
The README.md has a wealth of useful detail but it does not tell what pixis does or why we think it's useful.  I would suggest adding a "What is Pixis?" section at the beginning of the main README.md with text similar to the following:

_Pixis is Python-based tool to generate REST clients and servers from OpenAPI specifications. It is designed to set up in minutes, cover popular languages and REST frameworks, and be easy to extend.  We aim to create tooling that adapts well to a world of rapidly changing REST-based services running in environments like Kubernetes._ 

Feel free to adapt as you see fit!

**Comment by hodgesrm** [comment]
p.s., That's supposed to be italicized but markdown is not behaving. :(

**Comment by hodgesrm** [comment]
(Cut down the comment to something short and sweet.)

**Comment by andrew-ni** [comment]
Thanks Robert! Readme is now up to date

**Comment by hodgesrm** [comment]
Nice preface--better than my suggestion. Thanks!!
