### ISSUE TITLE
Need a way to suppress code generation on per-file basis

### ISSUE THREAD

**Issue by hodgesrm** [microservice-tools/pixis#33]
We need a simple way to suppress codegen that works down to the level of individual files.  It's common to encounter situations where code generation gives you 98% of what is needed but you need to edit the remaining 2% by hand (maybe after generating once). 

Swagger Codegen handles this pretty well using the .swagger-codegen-ignore file.  We should have a similar feature available as a setting in build.py which is our universal source of truth for code generation. 

(This is related to https://github.com/microservice-tools/pixis/issues/32)

**Comment by andrew-ni** [comment]
We're planning to implement this into the build file!

Users would define a list of file names and/or regular expressions, and we'll be able to test the filepath/names against these.

**Comment by andrew-ni** [comment]
Added in f99eaf4f23b4ce8741b3fa6a4cdc3845ba9afc1f
