### ISSUE TITLE
Pixis installation fails on Mac OS X unless pbr is installed first

### ISSUE THREAD

**Issue by hodgesrm** [microservice-tools/pixis#4]
Pixis installation fails on Mac OS X with Python 3.6.4 when installing from pixis:dev unless you install pbr first.   Steps to reproduce: 

```
$ python3 -m venv pixis-env
$ . pixis-env/bin/activate
(pixis-env) $ git clone https://github.com/microservice-tools/pixis
(pixis-env) $ cd pixis
(pixis-env) $ python3 setup.py develop
Download error on https://pypi.python.org/simple/pbr/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
Couldn't find index page for 'pbr' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
No local packages or working download links found for pbr>=1.9
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    'pixis=pixis.main:main',
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/Users/rhodges/workspaces/microservice-tools/pixis-env/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/Users/rhodges/workspaces/microservice-tools/pixis-env/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
    replace_conflicting=True,
  File "/Users/rhodges/workspaces/microservice-tools/pixis-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/rhodges/workspaces/microservice-tools/pixis-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/Users/rhodges/workspaces/microservice-tools/pixis-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/Users/rhodges/workspaces/microservice-tools/pixis-env/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
    return cmd.easy_install(req)
  File "/Users/rhodges/workspaces/microservice-tools/pixis-env/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.9')
```
Running `pip3 install pbr` fixes the problem.  This could be doc'ed in README.md then closed.

**Comment by hodgesrm** [comment]
There is a bit more to this issue.  I also had to run `pip3 install certifi` in order to get `python3 setup.py develop` to run cleanly.  See https://github.com/pypa/pip/issues/4205 for a description of the problem, which seems to be common on Mac OS X with Python 3.6.x.

**Comment by andrew-ni** [comment]
This is weird, we haven't seen this issue when testing but I think we're all using Python 3.5.2

We'll keep investigating, and hopefully once we start testing with tox we'll have a better answer for this

**Comment by hodgesrm** [comment]
It's apparently one of those problems that affects the dependency management, so that the tools can't fix it.

**Comment by hodgesrm** [comment]
I'll document behavior fully and submit a PR to fix--we'll have a few of these on different platforms.

**Comment by hodgesrm** [comment]
For anyone setting up on Mac OS X here's what currently works for me.  Using 10.11.6 (El Capitan) with Python 3.6.4 installed from python3.org. 
```
python3 -v venv pixis-env
python3 -m venv pixis-upstream
. pixis-upstream/bin/activate
git clone https://github.com/microservice-tools/pixis
cd pixis
pip install --upgrade pip
pip3 install pbr certifi
python3 setup.py develop
```
Key appears to be getting pbr and certifi into the environment so that installtools in setup.py can find other dependencies.  Upgrading pip3 gets rid of warnings but probably does not affect the outcome.

**Comment by DylonDickinson** [comment]
I have been using Mac OS X and haven't had this problem. My setup is 10.13.4 (High Sierra) with python 3.6.5. Without installing pdr or certifi I can run "python3 setup.py develop" without any issues.

**Comment by hodgesrm** [comment]
Hmm.  Did you install Python or are you using the version that comes pre-installed with Mac OS X?  I'm using the installed version from python.org. I'm also on an older Mac OS X rev (10.11.6), as noted above.

**Comment by hodgesrm** [comment]
That's probably the difference. I've had a lot of problems with Python installs on Mac OS X.  You could just add a note to run `pip3 install pbr certifi` if you have Mac OS X problems at the end of README.md and call it good.
