### ISSUE TITLE
How to add a new language to pixis?

### ISSUE THREAD

**Issue by hodgesrm** [microservice-tools/pixis#9]
This issue is intended to start a conversation about how to add new languages and REST frameworks. To keep the topic bounded this will treat languages only. 

The current implementation handles these topics as follows (from reading the code):
- Add a language: type support is in configurations.py.  This currently includes dictionaries to map OpenAPI types to Python and Typescript.  (I don't see where pixis handles name mapping e.g., to snake_case or camelCase.)
- Add a REST implementation: implementation support is pixis.languages. 

Enabling large numbers of languages contributed by different authors requires a comprehensive approach to language definition in pixis.  Here's a suggested way to frame the problem: 

1. It should be possible to add a new language without altering existing code, e.g., having to change configuration.py. 
2. Language dependencies should be encapsulated.  For example, type mappings depend not only on the type value but the format.  (Dates and UUIDs follow this pattern, as do numbers, e.g., integer/int64 in swagger.yaml.)  This is a function and may have further options like language version. 
3. Language dependencies should be comprehensive.  The following come lightly to mind. 
- Type mapping
- name case mapping, e.g., to snake_case
- JSON/XML serialization mechanisms
4. Languages should be cleanly separated from REST framework implementations. In other words we should factor responsibilities cleanly between language and framework implementations. 

To meet this framing here's a suggested set of changes.  
- Use a driver model in which language metadata are served up from a class that has standard methods like 'get_language_type', 'get_variable_name', 'get_serialization_method', etc. 
- An abstract Language class shows the required methods. 
- Each specific language implementation subclasses from the Language superclass.  Language subclasses can add additional methods for metadata useful to a particular language. 
- Users choose a REST implementation in build.py.  The REST implementation specifies the language it uses, and pixis will load the class automatically and pass it into invoked templates. 
- The pixis.languages module should contain language definition classes and the framework implementations currently there should move to pixis.frameworks. 

Let's consider a hypothetical Java implementation.  The steps to add Java language support would be as follows: 
1. Write java.py containing Java class implementation.
2. Place in pixis.languages whereupon pixis would find it automatically. 
3. Alternatively import in build.py and pass class reference as a build parameter. 

There's more to consider and we should discuss the relationship to framework implementations.  Looking forward to hearing thoughts from the team.

**Comment by JustinJiaDev** [comment]
Swift’s `Codable` design has a pretty simple yet good name mapping rule (https://forums.swift.org/t/jsonencoder-key-strategies/6958). 

And a silightly different rule written in JavaScript (https://github.com/sindresorhus/camelcase).

**Comment by JustinJiaDev** [comment]
I also want to share my two cents here. It would be great if `java.py` can also be placed outside internal languages folder. Pixis can therefore load external language definitions along with config files and templates. Ideally a user can have something like this:

- my-template
    - my-language.py (optional file)
    - my-config.py (optional file)
    - templates
        - controller.template
        - ...

And use it without modifying Pixis:

```
> pixis generate -t my-template
```

**Comment by hodgesrm** [comment]
@JustinJiaDev, Thanks for the comment! I was headed in a similar direction. 

To expand a little on your suggestion it would be interesting to come up with a model where the language support and templates tree structure you described is the same whether it's located in core pixis or in a user location.  If we get it right there might be a couple of nice benefits:
- Contributors could develop add-ons in separate Python modules.  As long as pixis can find them it's no different from having them in the core.
- Users could override language and templates behavior selectively by tweaking specific files.  In other words trees could be sparse and pixis would look for the rest in the core.

**Comment by andrew-ni** [comment]
Thanks for opening this discussion!

The current system we're developing is fairly simplistic. We would allow users to add new languages via the build file (containing type mapping and template emitting code) and an external templates folder. Name mapping would be handled via Jinja2 filters that we implement ( {{ myvariable | to_snake_case }} ).

I think the driver and language subclass approach that @hodgesrm is talking about is worth looking into, and would give us a more structured implementation for languages, and also move complexity out of our build file. I think it's important for users not to be able to modify our existing code, and store their custom assets externally, whether it's an add-on module or simple local files.

**Comment by granadata** [comment]
@andrew-ni I think you can do this in a step-wise fashion and still make quick forward progress.  The first step is to hive off language into the driver model discussed above.  This would start the tree structure that @JustinJiaDev  mentioned. The next step is to do something similar for frameworks.

**Comment by hodgesrm** [comment]
@andrew-ni You can get to the tree structure suggested by @JustinJiaDev incrementally.  The first step would be to hive off language support (i.e., extract from configuration.py), then tackle frameworks next.  This should not be too disruptive and should enable other work to continue in parallel.

**Comment by andrew-ni** [comment]
@hodgesrm I wanted to clarify a few points. With the structure we're aiming for, a user that wants to implement a new language would provide templates as well as 2 files - an implementation file (server_flask.py) as well as a language file if the language isn't supported (python.py). The implementation file will specify its language, and the user's build file will specify the implementation to use. In order for Pixis to understand all this, I'm having the user specify the relative paths in the build file. 

Does this seem like a good approach? I'm also going to be loading their files because I need to use their functions, similarly to how I load in their build file, but is this safe? I don't see any other way to do this so I just wanted to check.

**Comment by hodgesrm** [comment]
@andrew-ni , That approach sounds good to me.  You are right, the external files might be wrong in which case Pixis won't work but that's on the developers of new languages and frameworks to address. As a first step I would add solid docstrings to the language and framework .py files so that new users can tell what they are supposed to do. 

On a related topic I'm going to have a careful look at templates on Sunday morning and will post more thoughts about things that may be problematic for the Java implementation.  Would be great to hear if this also works for @kellysu95 in her node.js implementation.

**Comment by kellysu95** [comment]
@hodgesrm This sounds like a good approach that we can try to implement. So far, node.js is very similar in structure to the typescript client and python flask server template-wise in regards to the the generated services and controller files. Just like typescript and flask, there are similar framework or language-dependent specifics like name cases and type mappings that are based on type values and formats. It would be a good idea to have isolated subclasses for each language/framework where users can easily understand and define only the necessary configurations like @andrew-ni mentioned for their new language and have the core fill in as much of the work as possible for simplicity.

**Comment by hodgesrm** [comment]
OK, thanks @kellysu95 and @andrew-ni.  If you can make specific implementations sparse as @kellysu95 describes that would be great.  I'm starting on the Java templates in anticipation of refactored language support showing up in the next couple of days.

**Comment by andrew-ni** [comment]
@hodgesrm , languages/implementations factoring is mostly done on **languages** branch, and I'll have it done by tonight. I'll try to put in proper documentation for adding new languages as well.

I understand the problem with Config variables such as FLASK_SERVER_NAME and such, and I think a solution for this would be to have defaults for these variables, and allow the user to change/add them and use the values in their templates. With the new restructuring of language/implementation classes, this should be no problem!
